go_import_path: github.com/minio/minio

language: go

addons:
  apt:
    packages:
    - shellcheck

services:
  - docker

# this ensures PRs based on a local branch are not built twice
# the downside is that a PR targeting a different branch is not built
# but as a workaround you can add the branch to this list
branches:
  only:
    - master

matrix:
  include:
    - os: linux
      arch: ppc64le
      dist: bionic
      sudo: required
      env:
        - ARCH=ppc64le
        - CGO_ENABLED=0
        - GO111MODULE=on
      addons:
        apt:
          update: true
          packages:
            - jq
            - shellcheck
      go: 1.13.x
      script:
        - make
        - diff -au <(gofmt -s -d cmd) <(printf "")
        - diff -au <(gofmt -s -d pkg) <(printf "")
        - for d in $(go list ./... | grep -v browser); do CGO_ENABLED=1 go test -v --timeout 20m "$d"; done
        #- make test
        #- make test-race
        - make verifiers
        - make crosscompile
        - make verify
        - curl -o- -L https://yarnpkg.com/install.sh | bash
        - export PATH="$HOME/.yarn/bin:$PATH"
        - cd browser && yarn && yarn test && cd ..
        - bash -c 'shopt -s globstar; shellcheck mint/**/*.sh'

before_script:
  # Add an IPv6 config - see the corresponding Travis issue
  # https://github.com/travis-ci/travis-ci/issues/8361
  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then sudo sh -c 'echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6'; fi

before_install:
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then nvm install stable ; fi
